package com.ice.server.dao.model;

import java.util.Date;

public class IceApp {
  /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_app.id
     *
     * @mbg.generated
     */
    private Long id;

  /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_app.name
     *
     * @mbg.generated
     */
    private String name;

  /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_app.info
     *
     * @mbg.generated
     */
    private String info;

  /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_app.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

  /*
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_app.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

  /*
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_app.id
     *
     * @return the value of ice_app.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    public IceApp withId(Long id) {
        this.setId(id);
        return this;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_app.id
     *
     * @param id the value for ice_app.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_app.name
     *
     * @return the value of ice_app.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    public IceApp withName(String name) {
        this.setName(name);
        return this;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_app.name
     *
     * @param name the value for ice_app.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_app.info
     *
     * @return the value of ice_app.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    public IceApp withInfo(String info) {
        this.setInfo(info);
        return this;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_app.info
     *
     * @param info the value for ice_app.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_app.create_at
     *
     * @return the value of ice_app.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    public IceApp withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_app.create_at
     *
     * @param createAt the value for ice_app.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_app.update_at
     *
     * @return the value of ice_app.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    public IceApp withUpdateAt(Date updateAt) {
        this.setUpdateAt(updateAt);
        return this;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_app.update_at
     *
     * @param updateAt the value for ice_app.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IceApp other = (IceApp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getInfo() == null ? other.getInfo() == null : this.getInfo().equals(other.getInfo()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getUpdateAt() == null ? other.getUpdateAt() == null : this.getUpdateAt().equals(other.getUpdateAt()));
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getInfo() == null) ? 0 : getInfo().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getUpdateAt() == null) ? 0 : getUpdateAt().hashCode());
        return result;
    }

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", info=").append(info);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append("]");
        return sb.toString();
    }
}