package com.ice.server.dao.model;

import java.util.Date;

public class IceBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.app
     *
     * @mbg.generated
     */
    private Integer app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.scenes
     *
     * @mbg.generated
     */
    private String scenes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.conf_id
     *
     * @mbg.generated
     */
    private Long confId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.time_type
     *
     * @mbg.generated
     */
    private Byte timeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.start
     *
     * @mbg.generated
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.end
     *
     * @mbg.generated
     */
    private Date end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.debug
     *
     * @mbg.generated
     */
    private Byte debug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.priority
     *
     * @mbg.generated
     */
    private Long priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_base.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.id
     *
     * @return the value of tb_ice_base.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.id
     *
     * @param id the value for tb_ice_base.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.name
     *
     * @return the value of tb_ice_base.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.name
     *
     * @param name the value for tb_ice_base.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.app
     *
     * @return the value of tb_ice_base.app
     *
     * @mbg.generated
     */
    public Integer getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withApp(Integer app) {
        this.setApp(app);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.app
     *
     * @param app the value for tb_ice_base.app
     *
     * @mbg.generated
     */
    public void setApp(Integer app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.scenes
     *
     * @return the value of tb_ice_base.scenes
     *
     * @mbg.generated
     */
    public String getScenes() {
        return scenes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withScenes(String scenes) {
        this.setScenes(scenes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.scenes
     *
     * @param scenes the value for tb_ice_base.scenes
     *
     * @mbg.generated
     */
    public void setScenes(String scenes) {
        this.scenes = scenes == null ? null : scenes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.status
     *
     * @return the value of tb_ice_base.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.status
     *
     * @param status the value for tb_ice_base.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.conf_id
     *
     * @return the value of tb_ice_base.conf_id
     *
     * @mbg.generated
     */
    public Long getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withConfId(Long confId) {
        this.setConfId(confId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.conf_id
     *
     * @param confId the value for tb_ice_base.conf_id
     *
     * @mbg.generated
     */
    public void setConfId(Long confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.time_type
     *
     * @return the value of tb_ice_base.time_type
     *
     * @mbg.generated
     */
    public Byte getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withTimeType(Byte timeType) {
        this.setTimeType(timeType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.time_type
     *
     * @param timeType the value for tb_ice_base.time_type
     *
     * @mbg.generated
     */
    public void setTimeType(Byte timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.start
     *
     * @return the value of tb_ice_base.start
     *
     * @mbg.generated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withStart(Date start) {
        this.setStart(start);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.start
     *
     * @param start the value for tb_ice_base.start
     *
     * @mbg.generated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.end
     *
     * @return the value of tb_ice_base.end
     *
     * @mbg.generated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withEnd(Date end) {
        this.setEnd(end);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.end
     *
     * @param end the value for tb_ice_base.end
     *
     * @mbg.generated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.debug
     *
     * @return the value of tb_ice_base.debug
     *
     * @mbg.generated
     */
    public Byte getDebug() {
        return debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withDebug(Byte debug) {
        this.setDebug(debug);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.debug
     *
     * @param debug the value for tb_ice_base.debug
     *
     * @mbg.generated
     */
    public void setDebug(Byte debug) {
        this.debug = debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.priority
     *
     * @return the value of tb_ice_base.priority
     *
     * @mbg.generated
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withPriority(Long priority) {
        this.setPriority(priority);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.priority
     *
     * @param priority the value for tb_ice_base.priority
     *
     * @mbg.generated
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.create_at
     *
     * @return the value of tb_ice_base.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.create_at
     *
     * @param createAt the value for tb_ice_base.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_base.update_at
     *
     * @return the value of tb_ice_base.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    public IceBase withUpdateAt(Date updateAt) {
        this.setUpdateAt(updateAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_base.update_at
     *
     * @param updateAt the value for tb_ice_base.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IceBase other = (IceBase) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getApp() == null ? other.getApp() == null : this.getApp().equals(other.getApp()))
            && (this.getScenes() == null ? other.getScenes() == null : this.getScenes().equals(other.getScenes()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getConfId() == null ? other.getConfId() == null : this.getConfId().equals(other.getConfId()))
            && (this.getTimeType() == null ? other.getTimeType() == null : this.getTimeType().equals(other.getTimeType()))
            && (this.getStart() == null ? other.getStart() == null : this.getStart().equals(other.getStart()))
            && (this.getEnd() == null ? other.getEnd() == null : this.getEnd().equals(other.getEnd()))
            && (this.getDebug() == null ? other.getDebug() == null : this.getDebug().equals(other.getDebug()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getUpdateAt() == null ? other.getUpdateAt() == null : this.getUpdateAt().equals(other.getUpdateAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getApp() == null) ? 0 : getApp().hashCode());
        result = prime * result + ((getScenes() == null) ? 0 : getScenes().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getConfId() == null) ? 0 : getConfId().hashCode());
        result = prime * result + ((getTimeType() == null) ? 0 : getTimeType().hashCode());
        result = prime * result + ((getStart() == null) ? 0 : getStart().hashCode());
        result = prime * result + ((getEnd() == null) ? 0 : getEnd().hashCode());
        result = prime * result + ((getDebug() == null) ? 0 : getDebug().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getUpdateAt() == null) ? 0 : getUpdateAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", app=").append(app);
        sb.append(", scenes=").append(scenes);
        sb.append(", status=").append(status);
        sb.append(", confId=").append(confId);
        sb.append(", timeType=").append(timeType);
        sb.append(", start=").append(start);
        sb.append(", end=").append(end);
        sb.append(", debug=").append(debug);
        sb.append(", priority=").append(priority);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append("]");
        return sb.toString();
    }
}