package com.ice.server.dao.model;

import java.util.Date;

public class IcePushHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.app
     *
     * @mbg.generated
     */
    private Integer app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.ice_id
     *
     * @mbg.generated
     */
    private Long iceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ice_push_history.push_data
     *
     * @mbg.generated
     */
    private String pushData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.id
     *
     * @return the value of tb_ice_push_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.id
     *
     * @param id the value for tb_ice_push_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.app
     *
     * @return the value of tb_ice_push_history.app
     *
     * @mbg.generated
     */
    public Integer getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withApp(Integer app) {
        this.setApp(app);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.app
     *
     * @param app the value for tb_ice_push_history.app
     *
     * @mbg.generated
     */
    public void setApp(Integer app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.ice_id
     *
     * @return the value of tb_ice_push_history.ice_id
     *
     * @mbg.generated
     */
    public Long getIceId() {
        return iceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withIceId(Long iceId) {
        this.setIceId(iceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.ice_id
     *
     * @param iceId the value for tb_ice_push_history.ice_id
     *
     * @mbg.generated
     */
    public void setIceId(Long iceId) {
        this.iceId = iceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.reason
     *
     * @return the value of tb_ice_push_history.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withReason(String reason) {
        this.setReason(reason);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.reason
     *
     * @param reason the value for tb_ice_push_history.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.operator
     *
     * @return the value of tb_ice_push_history.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withOperator(String operator) {
        this.setOperator(operator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.operator
     *
     * @param operator the value for tb_ice_push_history.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.create_at
     *
     * @return the value of tb_ice_push_history.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.create_at
     *
     * @param createAt the value for tb_ice_push_history.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ice_push_history.push_data
     *
     * @return the value of tb_ice_push_history.push_data
     *
     * @mbg.generated
     */
    public String getPushData() {
        return pushData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    public IcePushHistory withPushData(String pushData) {
        this.setPushData(pushData);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ice_push_history.push_data
     *
     * @param pushData the value for tb_ice_push_history.push_data
     *
     * @mbg.generated
     */
    public void setPushData(String pushData) {
        this.pushData = pushData == null ? null : pushData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IcePushHistory other = (IcePushHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApp() == null ? other.getApp() == null : this.getApp().equals(other.getApp()))
            && (this.getIceId() == null ? other.getIceId() == null : this.getIceId().equals(other.getIceId()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getPushData() == null ? other.getPushData() == null : this.getPushData().equals(other.getPushData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApp() == null) ? 0 : getApp().hashCode());
        result = prime * result + ((getIceId() == null) ? 0 : getIceId().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getPushData() == null) ? 0 : getPushData().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", app=").append(app);
        sb.append(", iceId=").append(iceId);
        sb.append(", reason=").append(reason);
        sb.append(", operator=").append(operator);
        sb.append(", createAt=").append(createAt);
        sb.append(", pushData=").append(pushData);
        sb.append("]");
        return sb.toString();
    }
}