package com.ice.server.dao.mapper;

import com.ice.server.dao.model.IceApp;
import com.ice.server.dao.model.IceAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IceAppMapper {
  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    long countByExample(IceAppExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int deleteByExample(IceAppExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int insert(IceApp record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int insertSelective(IceApp record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    List<IceApp> selectByExample(IceAppExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    IceApp selectByPrimaryKey(Long id);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IceApp record, @Param("example") IceAppExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IceApp record, @Param("example") IceAppExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IceApp record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IceApp record);
}