package com.ice.server.dao.mapper;

import com.ice.server.dao.model.IceBase;
import com.ice.server.dao.model.IceBaseExample;
import java.util.List;

import com.ice.server.dao.model.IceConf;
import org.apache.ibatis.annotations.Param;

public interface IceBaseMapper {
  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    long countByExample(IceBaseExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int deleteByExample(IceBaseExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int insert(IceBase record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int insertSelective(IceBase record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_conf
     *
     * @mbg.generated
     */
    int insertSelectiveWithId(IceBase record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    List<IceBase> selectByExample(IceBaseExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    IceBase selectByPrimaryKey(Long id);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IceBase record, @Param("example") IceBaseExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IceBase record, @Param("example") IceBaseExample example);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IceBase record);

  /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IceBase record);
}