package com.ice.server.dao.mapper;

import com.ice.server.dao.model.IcePushHistory;
import com.ice.server.dao.model.IcePushHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcePushHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    long countByExample(IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int deleteByExample(IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int insert(IcePushHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int insertSelective(IcePushHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    List<IcePushHistory> selectByExampleWithBLOBs(IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    List<IcePushHistory> selectByExample(IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    IcePushHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IcePushHistory record, @Param("example") IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") IcePushHistory record, @Param("example") IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IcePushHistory record, @Param("example") IcePushHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IcePushHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(IcePushHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ice_push_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IcePushHistory record);
}