// Command ice-scan scans Go source packages for leaf node roam key accesses
// and generates a roam_keys_gen.go file containing the scan results.
//
// Usage:
//
//	ice-scan -dir ./path/to/leafpkg -out ./path/to/output/roam_keys_gen.go -pkg mypkg
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/zjn-zjn/ice/sdks/go/scan"
)

func main() {
	dir := flag.String("dir", ".", "directory to scan for leaf node source files")
	recursive := flag.Bool("r", false, "recursively scan subdirectories")
	outFile := flag.String("out", "", "output file path (default: stdout as JSON)")
	outPkg := flag.String("pkg", "", "package name for generated Go file (requires -out)")
	jsonOut := flag.Bool("json", false, "output as JSON instead of Go code")
	flag.Parse()

	var results []scan.ScanResult
	var err error

	if *recursive {
		results, err = scan.ScanDir(*dir)
	} else {
		results, err = scan.ScanPackage(*dir)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan error: %v\n", err)
		os.Exit(1)
	}

	if len(results) == 0 {
		fmt.Fprintln(os.Stderr, "no roam key accesses found")
		return
	}

	if *jsonOut || *outFile == "" {
		// JSON output
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(results); err != nil {
			fmt.Fprintf(os.Stderr, "json encode error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	// Generate Go file
	pkg := *outPkg
	if pkg == "" {
		pkg = "main"
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by ice-scan. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	sb.WriteString("import \"github.com/zjn-zjn/ice/sdks/go/dto\"\n\n")
	sb.WriteString("// RoamKeysMap maps struct name to its roam key metadata.\n")
	sb.WriteString("var RoamKeysMap = map[string][]dto.RoamKeyMeta{\n")

	for _, r := range results {
		jsonBytes, err := json.Marshal(r.RoamKeys)
		if err != nil {
			continue
		}
		// Convert JSON to Go literal (approximate - use raw JSON in a helper)
		sb.WriteString(fmt.Sprintf("\t%q: mustParseRoamKeys(`%s`),\n", r.ClassName, string(jsonBytes)))
	}
	sb.WriteString("}\n\n")

	// Helper function
	sb.WriteString(`func mustParseRoamKeys(raw string) []dto.RoamKeyMeta {
	var keys []dto.RoamKeyMeta
	if err := json.Unmarshal([]byte(raw), &keys); err != nil {
		panic("ice-scan: bad generated roam keys: " + err.Error())
	}
	return keys
}
`)

	// Need to add encoding/json import
	content := sb.String()
	content = strings.Replace(content,
		"import \"github.com/zjn-zjn/ice/sdks/go/dto\"\n",
		"import (\n\t\"encoding/json\"\n\n\t\"github.com/zjn-zjn/ice/sdks/go/dto\"\n)\n",
		1)

	if err := os.WriteFile(*outFile, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "generated %s with %d struct(s)\n", *outFile, len(results))
}
