server:
  port: 8121
spring:
  datasource:
    url: jdbc:dm://127.0.0.1:5236/ice?schema=ICE&useUnicode=true&characterEncoding=UTF-8
    username: waitmoon
    password: waitmoon
ice:
  port: 18121
  pool:
    core-size: 4
    max-size: 4
    keep-alive-seconds: 60
    queue-capacity: 60000
#  ha: #now default zk
#    address: localhost:2181,localhost:2182,localhost:2183
environment: prod