// Code generated by ice-scan. DO NOT EDIT.

package main

import (
	"encoding/json"

	"github.com/zjn-zjn/ice/sdks/go/dto"
)

// RoamKeysMap maps struct name to its roam key metadata.
var RoamKeysMap = map[string][]dto.RoamKeyMeta{
	"ScoreFlow": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]}]`),
	"ScoreFlow2": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]}]`),
	"AmountResult": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]},{"direction":"write","accessMode":"direct","accessMethod":"put","keyParts":[{"type":"literal","value":"SEND_AMOUNT"}]}]`),
	"AmountResult2": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]},{"direction":"write","accessMode":"direct","accessMethod":"put","keyParts":[{"type":"literal","value":"SEND_AMOUNT"}]}]`),
	"PointResult2": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]},{"direction":"write","accessMode":"direct","accessMethod":"put","keyParts":[{"type":"literal","value":"SEND_POINT"}]}]`),
	"InitConfigResult": mustParseRoamKeys(`[{"direction":"write","accessMode":"direct","accessMethod":"put","keyParts":[{"type":"field","ref":"ConfigKey"}]}]`),
	"PointResult": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]},{"direction":"write","accessMode":"direct","accessMethod":"put","keyParts":[{"type":"literal","value":"SEND_POINT"}]}]`),
	"RoamProbeLogNone": mustParseRoamKeys(`[{"direction":"read","accessMode":"direct","accessMethod":"getDeep","keyParts":[{"type":"field","ref":"Key"}]}]`),
}

func mustParseRoamKeys(raw string) []dto.RoamKeyMeta {
	var keys []dto.RoamKeyMeta
	if err := json.Unmarshal([]byte(raw), &keys); err != nil {
		panic("ice-scan: bad generated roam keys: " + err.Error())
	}
	return keys
}
